annotations:
  group: fun.freechat
app-template:
  persistence:
    data:
      storageClass: 'default'
      retain: true
  service:
    main:
      controller: main
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
      ports:
        http:
          port: 18789
        voice:
          port: 3334
